// This file is auto-generated by generate-approved-song-ids.ts. Do not edit manually.
export const approvedSongIds = [

] as const;

export const approvedSongIdSet = new Set<string>(approvedSongIds);
