import * as fs from 'fs';
import * as path from 'path';
import { songs } from '../src/data/songs';

const reviewFilePath = path.join(__dirname, '../src/data/reviews/song-review-status.json');
const outputPath = path.join(__dirname, '../src/data/reviews/approved-song-ids.generated.ts');

function generate() {
  console.log('🏁 Generating approved song IDs from review status...');
  
  if (!fs.existsSync(reviewFilePath)) {
    console.log('⚠️ No review status file found. Generating empty approved ID list.');
    writeEmptyOutput();
    return;
  }

  const rawData = fs.readFileSync(reviewFilePath, 'utf8');
  let reviews: any[] = [];
  try {
    const parsed = JSON.parse(rawData);
    reviews = Array.isArray(parsed) ? parsed : (parsed.reviews || []);
  } catch (error) {
    console.error('❌ Failed to parse song-review-status.json:', error);
    process.exit(1);
  }

  const approvedIds = new Set<string>();
  const allSongIds = new Set(songs.map(s => s.id));

  const checklistKeys = [
    'impressionIsAccurate',
    'tagsAreAccurate',
    'seasonHasEvidence',
    'recommendationFits',
    'noOverstatement',
    'copyIsDistinct',
    'rankingFeelsNatural'
  ];

  for (const review of reviews) {
    const { songId, reviewed, checks } = review;

    // 1. Verify song exists in catalog database
    if (!allSongIds.has(songId)) {
      console.error(`❌ Validation Error: Song ID [${songId}] found in review status does not exist in the active song list!`);
      process.exit(1);
    }

    // 2. Validate reviewed flag
    if (reviewed !== true) {
      continue;
    }

    // 3. Validate all 7 checklist keys are true
    if (!checks) {
      continue;
    }
    const allChecksPass = checklistKeys.every(key => checks[key] === true);
    if (!allChecksPass) {
      continue;
    }

    approvedIds.add(songId);
  }

  // 4. Stable sort
  const sortedIds = Array.from(approvedIds).sort();

  const outputContent = `// This file is auto-generated by generate-approved-song-ids.ts. Do not edit manually.
export const approvedSongIds = [
${sortedIds.map(id => `  "${id}"`).join(',\n')}
] as const;

export const approvedSongIdSet = new Set<string>(approvedSongIds);
`;

  const outputDir = path.dirname(outputPath);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  // Write atomically
  const tempPath = outputPath + '.tmp';
  fs.writeFileSync(tempPath, outputContent, 'utf8');
  fs.renameSync(tempPath, outputPath);

  console.log(`✅ Successfully generated approved song IDs file at: ${outputPath}`);
  console.log(`   Total approved songs: ${sortedIds.length}`);
}

function writeEmptyOutput() {
  const emptyContent = `// This file is auto-generated by generate-approved-song-ids.ts. Do not edit manually.
export const approvedSongIds = [] as const;

export const approvedSongIdSet = new Set<string>();
`;
  const outputDir = path.dirname(outputPath);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }
  fs.writeFileSync(outputPath, emptyContent, 'utf8');
}

generate();
